# matrix
matrix:
  dist: xenial
  python:
  # - 3.6
  - 3.7
  include:
  - name: "Python 3.7 on macOS"
    os: osx
    language: shell
    before_script:
    - echo $PATH
    - pwd
  # - name: "Python 3.7 on Windows"
  #   os: windows
  #   language: shell
  #   env: export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
  #   before_install: choco install python3
  #   before_script:
  #   - echo 'path'

# before install
before_install:
  - pip3 install --upgrade pip setuptools virtualenv psd-tools opencv-python pipenv
  - python3 -m venv env
  - source env/bin/activate
  - pip3 install certifi
  - pip3 install pytest allure-pytest pytest-html

# command to install dependencies and package
install:
  - pip3 install -r requirements.txt
  - python3 setup.py install

# command to run tests, e.g. python setup.py test
script:
  - pytest --html=report.html --self-contained-html
