# based on https://github.com/matplotlib/matplotlib/blob/master/.travis.yml
language: python

cache:
  pip: true
  directories:
    # https://github.com/travis-ci/travis-ci/issues/5853
    - $HOME/.ccache
    - $HOME/.cache/matplotlib

env:
  global:
    - ARTIFACTS_AWS_REGION=us-east-1
    - ARTIFACTS_BUCKET=matplotlib-test-results
    # Variables controlling the build.
    - MPLLOCALFREETYPE=1
    # Variables controlling the test run.
    - DELETE_FONT_CACHE=
    - NO_AT_BRIDGE=1  # Necessary for GTK3 interactive test.
    # The number of processes is hardcoded.
    - NPROC=2
    - OPENBLAS_NUM_THREADS=1
    - PYTHONFAULTHANDLER=1
    - PYTEST_ADDOPTS="-raR --log-level=DEBUG"
    - RUN_PYTEST=1
    - PATH=${TRAVIS_BUILD_DIR}/python/bin:$PATH
    - PLATFORM=${TRAVIS_OS_NAME}

# matrix
matrix:
  include:
    - name: "Python 3.6 on OSX"
      python: 3.6
      sudo: true
      os: osx
      # https://github.com/travis-ci/travis-ci/issues/2312
      language: shell
      only: master
      cache:
        # As for now travis caches only "$HOME/.cache/pip".
        # https://docs.travis-ci.com/user/caching/#pip-cache
        pip: false
        directories:
          - $HOME/Library/Caches/pip
          # `cache` does not support `env`-like `global` so copy-paste from top.
          # https://github.com/travis-ci/travis-ci/issues/5853
          - $HOME/.ccache
          - $HOME/.cache/matplotlib

# before install
before_install: |
  # test with non-ascii in path.
  if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
    export PATH=/usr/lib/ccache:$PATH
    which python
    python --version
  fi

# command to install dependencies and package
install:
  - |
    # Which version of python.
    which python
    python --version
  - |
    # Setup environment.
    ccache -s
    git describe
    # Upgrade pip and setuptools and wheel to get as clean an install as possible.
    python3 -m pip install --upgrade pip setuptools wheel
  - |
    # Install from PiPY.
    # Install package dependencies.
    python3 -m pip install --quiet -r mdl/tests/dist/requirements.txt
    # Install pytest dependencies.
    python3 -m pip install --quiet -r mdl/tests/dist/pytest_requirements.txt
    # Install package.
    # python3 -m pip install --quiet -ve .
    python3 -m pip install --quiet imhr

before_script: 
  - |
    # get environment variables.
    # get current path.
    bash -c 'echo $PWD'
    # get repository directory path.
    bash -c 'echo $TRAVIS_BUILD_DIR'
    # get package path.
    bash -c 'echo $PATH'
    # get package path.
    echo $PATH
    # get python version.
    bash -c 'echo $TRAVIS_PYTHON_VERSION'
    # get python version test.
    bash -c 'echo PLATFORM'
  - |
    # delete cache.
    if [[ $DELETE_FONT_CACHE == 1 ]]; then
      rm -rf ~/.cache/matplotlib
    fi

# command to run tests, e.g. python setup.py test
script:
  # each script we want to run need to go in it's own section and the program you want
  # to fail travis need to be the last thing called.
  - |
    if [[ $RUN_PYTEST == 1 ]]; then
      echo "Calling pytest with the following arguments: $PYTEST_ADDOPTS"
      python3 -m pytest --html=report.html --self-contained-html
    fi
  
before_cache: |
  rm -rf $HOME/.cache/matplotlib/tex.cache
  rm -rf $HOME/.cache/matplotlib/test_cache
