sudo: true
# command to install dependencies
install:
  - pip install -r requirements.txt
dist: trusty
dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# running Python tests on multiple operating systems
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH  
branches:
  only:
  - master
# addons:
#   apt:
#     packages:
#       - chromium-chromedriver
# before_script:
#   - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
# env:
#   global:
#     # AWS_ACCESS_KEY_ID
#     - secure: 
# before_install:
#   - export PATH="$HOME/miniconda/bin:$PATH"
#   - export PATH="$HOME/miniconda/envs/testenv/bin:$PATH"
#   - export PATH="$HOME/build/bokeh/bokeh/bokehjs/node_modules/phantomjs-prebuilt/lib/phantom/bin:$PATH"
#   - export PATH="$HOME/bin:$PATH"
#   - export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
# jobs:
#   include:
#     - stage: build
#       install: scripts/ci/install.build
#       script: scripts/ci/build

#     - stage: test
#       install: scripts/ci/install.test
#       script: scripts/ci/test
#       addons:
#         chrome: stable
#       before_script:
#         - google-chrome-stable --no-sandbox --headless --hide-scrollbars --remote-debugging-port=9222 &
#       env:
#       - GROUP=examples
#       - PYTHON=3.5
#     - install: scripts/ci/install.test
#       script: scripts/ci/test
#       env:
#       - GROUP=examples
#       - PYTHON=2.7
#       - EXTRA_CMD=--no-js
