sudo: true
# command to install dependencies
install:
  - pip install -r requirements.txt
dist: trusty
dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  - "nightly"  # nightly build
branches:
  only:
    - master
# command to run tests
# install:
#   - make build
script:
  - echo "TODO"
# jobs:
#   include:
#     - stage: build
#       install: tests/ci/install.build
#       script: tests/ci/build
