# language
language: python

# matrix
matrix:
  dist: xenial
  python: 3.7
  include:
  - name: "Python 3.7 on macOS"
    os: osx
    language: shell
    before_script:
    - echo $PATH
    - pwd
  # - name: "Python 3.7 on Windows"
  #   os: windows
  #   language: shell
  #   env: export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
  #   before_install: choco install python3
  #   before_script:
  #   - echo 'path'

# before install
before_install:
  - pip3 install certifi
  - pip3 install --upgrade pip setuptools virtualenv psd-tools opencv-python

# command to install dependencies and package
install:
  - pip3 install -requirement requirements.txt
  - pip3 install certifi
  - python3 setup.py install || python setup.py install

# command to run tests
script: python3 mdl/tests/generate_roi.py || python mdl/tests/generate_roi.py 
