
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-02T17:01:16-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "9bd12dfbbd02d0c5f609a087033132b240c287a2",
 "version": "0.3.37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
